
networks:
  tycho:
    external: true

services:

  redis:
    image: redis:latest
    restart: always
    ports:
      - "7777:7777"
    environment:
      - BUILD_TYPE=release
      - REDIS_HOST=redis
      - REDIS_PORT=7777
      - REDIS_ARGS="--loglevel verbose"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 5
    networks:
      - tycho

  stream:
      build: 
       context: ..
       dockerfile: ops/Dockerfile
       args:
        - PROGRAM=stream
      volumes:
        - .:/app
      depends_on:
        redis:
          condition: service_healthy
      environment:
        - BUILD_TYPE=release
        - REDIS_HOST=redis
        - TESTING=true
        - TYCHO_URL=https://tycho-beta.propellerheads.xyz
        - TYCHO_API_KEY=sampletoken
        - HEARTBEAT=ToDo
      restart: always
      networks:
        - tycho

  api:
      build: 
       context: ..
       dockerfile: ops/Dockerfile
       args:
        - PROGRAM=api
      ports:
        - "3000:3000"
      volumes:
        - .:/app
      depends_on:
        redis:
          condition: service_healthy
      environment:
        - BUILD_TYPE=release
        - REDIS_HOST=redis
        - TESTING=true
        - TYCHO_URL=https://tycho-beta.propellerheads.xyz
        - TYCHO_API_KEY=sampletoken
        - HEARTBEAT=ToDo
      restart: always
      networks:
        - tycho
